-- Security audit records are server-only. No browser role receives table access.
create table if not exists public.admin_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  ip_hash text not null check (char_length(ip_hash) = 64),
  user_agent text,
  success boolean not null,
  failure_reason text
);

create index if not exists admin_login_events_created_at_idx
  on public.admin_login_events (created_at desc);

create index if not exists admin_login_events_user_id_idx
  on public.admin_login_events (user_id, created_at desc);

alter table public.admin_login_events enable row level security;

revoke all on table public.admin_login_events from anon, authenticated;
grant all on table public.admin_login_events to service_role;

grant usage, select on sequence public.admin_login_events_id_seq to service_role;

comment on table public.admin_login_events is
  'Server-only security audit trail for Fico Mana administrator sign-in attempts.';
