'use client'
import { useCachedPageRead } from '@/components/use-cached-page-read'

import { useEffect, useMemo, useRef, useState } from 'react'
import { ExternalLink, FolderSync, LoaderCircle, LogIn, QrCode, RefreshCw, Unplug, X } from 'lucide-react'
import AdminPageHeader from '@/components/admin-page-header'
import { useAdminToast } from '@/components/admin-toast-provider'
import PortalQrCode from '@/components/portal-qr-code'
import { adminInput, adminPanel, adminSelect } from '@/lib/admin-ui'
import { filterAndSortClientPortals, provisioningStatuses, type PortalListSort, type ProvisioningStatus } from '@/lib/client-portal-list'

type Portal={id:string;publicId:string;status:'active'|'disabled'|'expired';expiresAt:string|null}
type Item={bookingId:string;customerName:string;customerEmail:string;shootDate:string;packageName:string;bookingStatus:string;paymentStatus:string;requiredDeposit:number;provisioningStatus:'NOT_STARTED'|'PROVISIONING'|'ACTIVE'|'PARTIAL_FAILURE'|'FAILED';driveClientFolderUrl:string|null;lastError:string|null;portal:Portal}
type Overview={items:Item[];googleDrive:{rootFolderId:string|null;rootFolderName:string;portalExpiryDays:number;oauthAppConfigured:boolean;connected:boolean;needsReconnect:boolean;accountEmail:string|null}}
type Snapshot={clientPortalUrl?:string;status?:string;lastError?:string}
type QrPortal={bookingId:string;customerName:string;portalUrl:string;status:Portal['status'];expiresAt:string|null}

function statusClass(status:Item['provisioningStatus']){return status==='ACTIVE'?'border-green-500/30 bg-green-500/10 text-green-300':status==='PROVISIONING'?'border-blue-500/30 bg-blue-500/10 text-blue-300':status==='PARTIAL_FAILURE'?'border-amber-500/30 bg-amber-500/10 text-amber-300':status==='FAILED'?'border-red-500/30 bg-red-500/10 text-red-300':'border-white/10 bg-white/[0.03] text-white/45'}

const actionButton='inline-flex cursor-pointer items-center justify-center gap-1 rounded-lg border border-white/15 px-2.5 py-2 text-caption font-semibold uppercase transition-all duration-200 hover:-translate-y-0.5 hover:border-white/35 hover:bg-white/[0.06] hover:text-white hover:shadow-[0_8px_20px_rgba(0,0,0,0.24)] active:translate-y-0 active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C4CEFF]/60 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 disabled:hover:border-white/15 disabled:hover:bg-transparent disabled:hover:shadow-none'
const actionLink='inline-flex cursor-pointer items-center gap-1 transition-colors duration-200 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C4CEFF]/60'

export default function ProvisioningPage(){
  const toast=useAdminToast();const[overview,setOverview,loading,setLoading,refreshing]=useCachedPageRead<Overview|null>('admin:provisioning',null);const[busyId,setBusyId]=useState('');const[portalAction,setPortalAction]=useState<{bookingId:string;kind:'open'|'qr'}|null>(null);const[qrPortal,setQrPortal]=useState<QrPortal|null>(null);const[search,setSearch]=useState('');const[rootFolderId,setRootFolderId]=useState(overview?.googleDrive.rootFolderId||'');const[expiryDays,setExpiryDays]=useState(String(overview?.googleDrive.portalExpiryDays||30));const[saving,setSaving]=useState(false)
  const[statusFilter,setStatusFilter]=useState<'ALL'|ProvisioningStatus>('ALL')
  const[sortBy,setSortBy]=useState<PortalListSort>('newest')
  const settingsRevision = useRef(0)
  const load=async()=>{setLoading(true);const revision=settingsRevision.current;try{const response=await fetch('/api/provisioning',{cache:'no-store',credentials:'include'});const data=await response.json().catch(()=>({})) as Overview&{error?:string};if(!response.ok)throw new Error(data.error||'Could not load provisioning.');setOverview(data);if(revision===settingsRevision.current){setRootFolderId(data.googleDrive.rootFolderId||'');setExpiryDays(String(data.googleDrive.portalExpiryDays||30))}}catch(error){toast.error('Provisioning unavailable',error instanceof Error?error.message:'Try again.')}finally{setLoading(false)}}
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const connected=params.get('drive_connected');const driveError=params.get('drive_error');if(connected)toast.success('Google Drive connected',`${connected} is now the studio Drive account.`);if(driveError)toast.error('Google Drive connection failed',driveError);if(connected||driveError)window.history.replaceState({},'', '/admin/provisioning');void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])
  const filtered=useMemo(()=>filterAndSortClientPortals(overview?.items||[],search,statusFilter,sortBy),[overview,search,statusFilter,sortBy])
  const counts=useMemo(()=>{const items=overview?.items||[];return{active:items.filter((item)=>item.provisioningStatus==='ACTIVE').length,attention:items.filter((item)=>['FAILED','PARTIAL_FAILURE'].includes(item.provisioningStatus)).length,waiting:items.filter((item)=>item.provisioningStatus==='NOT_STARTED').length}},[overview])
  const runAction=async(bookingId:string,action:'retry'|'disable_portal'|'enable_portal')=>{setBusyId(bookingId);try{const response=await fetch(`/api/bookings/${encodeURIComponent(bookingId)}/provisioning`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await response.json().catch(()=>({})) as Snapshot&{error?:string};if(!response.ok)throw new Error(data.error||'Provisioning action failed.');toast.success(action==='retry'?'Provisioning updated':'Portal updated',data.status==='ACTIVE'?`${bookingId} is fully active.`:data.lastError||`${bookingId} updated.`);await load()}catch(error){toast.error('Action failed',error instanceof Error?error.message:'Try again.')}finally{setBusyId('')}}
  const getPortalUrl=async(bookingId:string)=>{const response=await fetch(`/api/bookings/${encodeURIComponent(bookingId)}/provisioning`,{cache:'no-store',credentials:'include'});const data=await response.json().catch(()=>({})) as Snapshot&{error?:string};if(!response.ok||!data.clientPortalUrl)throw new Error(data.error||'Client Portal is not active. Try: enable or reprovision it, then try again.');return data.clientPortalUrl}
  const openPortal=(bookingId:string)=>{setPortalAction({bookingId,kind:'open'});const portalTab=window.open(`/admin/portal/${encodeURIComponent(bookingId)}`,'_blank','noopener,noreferrer');if(!portalTab)toast.error('Portal tab blocked','Allow pop-ups for admin.ficomana.com, then try again.');window.setTimeout(()=>setPortalAction(null),350)}
  const showPortalQr=async(item:Item)=>{const expiry=item.portal.expiresAt?Date.parse(item.portal.expiresAt):Number.NaN;const expired=item.portal.status==='expired'||(Number.isFinite(expiry)&&expiry<=Date.now());if(expired){toast.error('Portal QR expired','This QR expired with the Client Portal link. Try: press Enable to renew the portal, then open QR again.');return}if(item.portal.status!=='active'){toast.error('Portal QR unavailable','This portal is disabled. Try: press Enable, then open QR again.');return}setPortalAction({bookingId:item.bookingId,kind:'qr'});try{setQrPortal({bookingId:item.bookingId,customerName:item.customerName,portalUrl:await getPortalUrl(item.bookingId),status:item.portal.status,expiresAt:item.portal.expiresAt})}catch(error){toast.error('QR unavailable',error instanceof Error?error.message:'Try: provision or enable the Client Portal, then try again.')}finally{setPortalAction(null)}}
  const saveSettings=async(initializeRoot=false)=>{if(initializeRoot&&rootFolderId&&!window.confirm('Create a new app-managed FICOMANA SHOOTS root for future bookings? Existing Drive folders will not be deleted.'))return;setSaving(true);try{const response=await fetch('/api/integrations/google-drive',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({rootFolderId:initializeRoot?undefined:rootFolderId.trim()||undefined,portalExpiryDays:Number(expiryDays)||30,initializeRoot})});const data=await response.json().catch(()=>({})) as{error?:string;root_folder_id?:string};if(!response.ok)throw new Error(data.error||'Could not save Google Drive settings.');toast.success('Drive settings saved',initializeRoot?'A secure app-managed FICOMANA SHOOTS root is ready.':data.root_folder_id?'FICOMANA SHOOTS root verified.':'Settings updated.');await load()}catch(error){toast.error('Settings failed',error instanceof Error?error.message:'Try again.')}finally{setSaving(false)}}
  const disconnect=async()=>{if(!window.confirm('Disconnect the studio Google Drive account? Existing folders will not be deleted.'))return;setSaving(true);try{const response=await fetch('/api/integrations/google-drive/disconnect',{method:'POST',credentials:'include'});const data=await response.json().catch(()=>({})) as{error?:string};if(!response.ok)throw new Error(data.error||'Could not disconnect Google Drive.');toast.success('Google Drive disconnected','Existing folders remain untouched.');await load()}catch(error){toast.error('Disconnect failed',error instanceof Error?error.message:'Try again.')}finally{setSaving(false)}}
  const drive=overview?.googleDrive

  return <div className="w-full min-w-0 space-y-6 font-sans" data-testid="client-portals-page"><AdminPageHeader title="Client Portals" subtitle="Manage client links and photo folders." onRefresh={load} refreshing={refreshing}/>
    <div className="grid gap-4 md:grid-cols-3"><Metric label="Active projects" value={counts.active}/><Metric label="Needs attention" value={counts.attention}/><Metric label="Not provisioned" value={counts.waiting}/></div>
    <section className={`${adminPanel} space-y-5 p-5 md:p-6`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><FolderSync className="mt-0.5 size-5 shrink-0 text-[#C4CEFF]"/><div className="flex-1"><h2 className="text-sm font-semibold">Google Drive automation</h2><p className="mt-1 text-xs text-white/45">FICOMANA SHOOTS → MONTH → DAY → CLIENT NAME</p><p className={`mt-2 text-xs ${drive?.connected?'text-green-300':'text-white/45'}`}>{drive?.connected?`Connected as ${drive.accountEmail}`:'Connect the studio Google account once to enable production file workflows.'}</p></div><div className="flex gap-2">{drive?.connected?<button onClick={()=>void disconnect()} disabled={saving} className={`${actionButton} px-3 text-white/70`}><Unplug className="size-3.5"/>Disconnect</button>:drive?.oauthAppConfigured?<a href="/api/integrations/google-drive/connect" className="inline-flex cursor-pointer items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-caption font-semibold uppercase text-white transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#1a14e8] hover:shadow-[0_8px_20px_rgba(5,0,208,0.3)] active:translate-y-0 active:scale-[0.98]"><LogIn className="size-3.5"/>Connect Google Drive</a>:null}</div></div>
      {!drive?.oauthAppConfigured?<div className="border border-amber-500/20 bg-amber-500/[0.06] p-3 text-xs text-amber-200">Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to the production environment before connecting Drive.</div>:null}
      {drive?.needsReconnect?<div className="flex flex-col gap-3 border border-amber-500/25 bg-amber-500/[0.07] p-4 text-xs text-amber-100 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-3xl leading-relaxed">Reconnect once to let Fico Mana discover photos added directly inside Google Drive RAW folders. Google will request read-only Drive access; Fico Mana write access remains limited to app-managed files.</p><a href="/api/integrations/google-drive/connect" className="inline-flex cursor-pointer shrink-0 items-center justify-center gap-1.5 rounded-lg bg-amber-300 px-4 py-2.5 text-caption font-semibold uppercase text-black transition-all duration-200 hover:-translate-y-0.5 hover:bg-amber-200 hover:shadow-[0_8px_20px_rgba(252,211,77,0.2)] active:translate-y-0 active:scale-[0.98]"><LogIn className="size-3.5"/>Reconnect for RAW Sync</a></div>:null}
      <div className="grid items-start gap-3 xl:grid-cols-[minmax(0,1fr)_180px_auto]"><label className="flex h-full flex-col gap-1.5"><span className="text-caption uppercase tracking-wider text-white/40">FICOMANA SHOOTS root folder ID</span><input value={rootFolderId} onChange={(event)=>{settingsRevision.current++;setRootFolderId(event.target.value)}} placeholder="Google Drive folder ID" className={adminInput}/><span className="block text-caption leading-relaxed text-white/35">For secure Drive access, use Create New Root. A manually pasted folder may not be available to this app.</span></label><label className="flex h-full flex-col gap-1.5"><span className="text-caption uppercase tracking-wider text-white/40">Portal expiry days</span><input type="number" min={1} max={3650} value={expiryDays} onChange={(event)=>{settingsRevision.current++;setExpiryDays(event.target.value)}} className={adminInput}/><span className="block text-caption leading-relaxed text-white/35">From 1 to 3,650 days after the first successful portal-ready email.</span></label><div className="flex h-full flex-col gap-1.5"><span aria-hidden="true" className="invisible text-caption uppercase tracking-wider">Settings actions</span><div className="flex min-h-[42px] flex-wrap items-stretch gap-2"><button disabled={saving||!drive?.connected} onClick={()=>void saveSettings(false)} className={`${actionButton} px-4 py-2.5 text-caption`}>Verify & Save</button>{drive?.connected?<button disabled={saving} onClick={()=>void saveSettings(true)} className="inline-flex cursor-pointer items-center justify-center rounded-lg bg-primary px-4 py-2.5 text-caption font-semibold uppercase transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#1a14e8] hover:shadow-[0_8px_20px_rgba(5,0,208,0.3)] active:translate-y-0 active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 disabled:hover:shadow-none">{rootFolderId?'Create New Root':'Create Root'}</button>:null}</div><span aria-hidden="true" className="invisible block text-caption leading-relaxed">Settings actions</span></div></div>
      {rootFolderId?<a href={`https://drive.google.com/drive/folders/${encodeURIComponent(rootFolderId)}`} target="_blank" rel="noopener noreferrer" className={`${actionLink} text-xs text-[#C4CEFF]`}>Open FICOMANA SHOOTS <ExternalLink className="size-3.5"/></a>:null}
    </section>
    <div className={`${adminPanel} p-4`}>
      <div className="grid items-end gap-4 lg:grid-cols-[minmax(0,1fr)_200px_230px]">
        <label className="text-xs text-white/50">Search clients<input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Booking, client, package, or shoot date…" className={`${adminInput} mt-2`}/></label>
        <label className="text-xs text-white/50">Provisioning status<select value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value as 'ALL'|ProvisioningStatus)} className={`${adminSelect} mt-2`}><option value="ALL">All statuses</option>{provisioningStatuses.map(status=><option key={status.value} value={status.value}>{status.label}</option>)}</select></label>
        <label className="text-xs text-white/50">Sort by<select value={sortBy} onChange={(event)=>setSortBy(event.target.value as PortalListSort)} className={`${adminSelect} mt-2`}><option value="newest">Shoot date: newest first</option><option value="oldest">Shoot date: oldest first</option><option value="status">Status: needs attention first</option><option value="client">Client name: A–Z</option></select></label>
      </div>
      <p className="mt-3 text-xs text-white/40" role="status">Showing {filtered.length} of {overview?.items.length||0} clients</p>
    </div>
    <div className={`${adminPanel} overflow-x-auto`}>
      <table className="w-full min-w-[1160px] text-left text-xs">
        <thead><tr className="border-b border-white/10 bg-white/[0.03] text-caption uppercase tracking-wider text-white/40"><th className="p-4">Booking</th><th className="p-4">Shoot</th><th className="p-4">Provisioning</th><th className="p-4">Drive</th><th className="p-4">Client Portal</th><th className="min-w-[330px] p-4 text-right">Actions</th></tr></thead>
        <tbody className="divide-y divide-white/5">{filtered.map((item)=>{
          const rowBusy=busyId===item.bookingId
          const portalOpening=portalAction?.bookingId===item.bookingId&&portalAction.kind==='open'
          const portalQrLoading=portalAction?.bookingId===item.bookingId&&portalAction.kind==='qr'
          const portalBusy=portalOpening||portalQrLoading
          return <tr key={item.bookingId} className="align-middle [&>td]:align-middle transition-colors hover:bg-white/[0.02]">
            <td className="p-4"><p className="font-mono font-bold text-[#C4CEFF]">{item.bookingId}</p><p className="mt-1 font-semibold">{item.customerName}</p><p className="mt-0.5 text-caption text-white/40">{item.packageName}</p></td>
            <td className="p-4"><p className="font-semibold">{item.shootDate}</p><p className="mt-1 text-caption text-white/40">{item.bookingStatus} · {item.paymentStatus}</p></td>
            <td className="max-w-[260px] p-4"><span className={`inline-flex rounded-md border px-2 py-1 text-caption font-semibold uppercase ${statusClass(item.provisioningStatus)}`}>{item.provisioningStatus.replaceAll('_',' ')}</span>{item.lastError?<p className="mt-2 text-caption leading-relaxed text-red-300">{item.lastError}</p>:null}</td>
            <td className="p-4">{item.driveClientFolderUrl?<a href={item.driveClientFolderUrl} target="_blank" rel="noopener noreferrer" className={`${actionButton} min-h-10 whitespace-nowrap text-green-300`}>Open folder <ExternalLink className="size-3 shrink-0"/></a>:<span className="text-white/35">Not created</span>}</td>
            <td className="p-4">{item.portal?<p className="flex items-center gap-2 whitespace-nowrap"><span className={`inline-flex rounded-md border px-2 py-1 text-caption font-semibold capitalize ${item.portal.status==='active'?'border-green-500/30 bg-green-500/10 text-green-300':item.portal.status==='expired'?'border-amber-500/30 bg-amber-500/10 text-amber-300':'border-white/10 bg-white/[0.03] text-white/45'}`}>{item.portal.status}</span>{item.portal.expiresAt?<span className="text-caption text-white/40">Expires {new Date(item.portal.expiresAt).toLocaleDateString('en-PH')}</span>:null}</p>:<span className="text-white/35">Not created</span>}</td>
            <td className="min-w-[330px] p-4"><div className="flex flex-wrap items-center justify-end gap-3 [&>button]:px-3 [&>button]:py-2.5">
              {item.provisioningStatus==='NOT_STARTED'||item.provisioningStatus==='FAILED'||item.provisioningStatus==='PARTIAL_FAILURE'?<button disabled={rowBusy||!drive?.connected} onClick={()=>void runAction(item.bookingId,'retry')} className={actionButton}><RefreshCw className={`size-3 ${rowBusy?'animate-spin':''}`}/>{item.provisioningStatus==='NOT_STARTED'?'Provision':'Retry failed setup'}</button>:null}
              {item.portal?<>
                <button disabled={portalBusy||rowBusy} aria-busy={portalOpening} onClick={()=>void openPortal(item.bookingId)} className={actionButton}>{portalOpening?<LoaderCircle className="size-3 animate-spin"/>:<ExternalLink className="size-3"/>}{portalOpening?'Opening…':'Portal'}</button>
                <button disabled={portalBusy||rowBusy} aria-busy={portalQrLoading} onClick={()=>void showPortalQr(item)} className={actionButton}>{portalQrLoading?<LoaderCircle className="size-3 animate-spin"/>:<QrCode className="size-3"/>}{portalQrLoading?'Loading…':'QR'}</button>
                <button disabled={rowBusy||portalBusy} onClick={()=>void runAction(item.bookingId,item.portal.status==='active'?'disable_portal':'enable_portal')} className={`${actionButton} ${item.portal.status==='active'?'border-red-500/25 text-red-200 hover:bg-red-500/10':''}`}>{rowBusy?'Updating…':item.portal.status==='active'?'Disable portal':'Enable portal'}</button>
              </>:null}
            </div></td>
          </tr>
        })}{!loading&&!filtered.length?<tr><td colSpan={6} className="p-10 text-center text-sm text-white/45">No clients match these filters. Try: choose All statuses or change your search.</td></tr>:null}</tbody>
      </table>
    </div>
    {qrPortal?<PortalQrDialog portal={qrPortal} onClose={()=>setQrPortal(null)}/>:null}
  </div>
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-card border border-white/10 bg-white/[0.02] p-5"><p className="text-caption uppercase tracking-wider text-white/40">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}

function PortalQrDialog({portal,onClose}:{portal:QrPortal;onClose:()=>void}){
  return <div className="fixed inset-0 z-[90] flex items-center justify-center overflow-y-auto bg-black/85 p-4 backdrop-blur-sm" onClick={onClose}>
    <div role="dialog" aria-modal="true" aria-labelledby="portal-qr-title" className="relative my-auto w-full max-w-md rounded-card border border-white/15 bg-[#1d1d1d] p-5 shadow-2xl sm:p-7" onClick={(event)=>event.stopPropagation()}>
      <button type="button" onClick={onClose} aria-label="Close client portal QR" className="absolute right-3 top-3 inline-flex size-9 cursor-pointer items-center justify-center rounded-full border border-white/10 text-white/55 transition hover:border-white/30 hover:bg-white/[0.06] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C4CEFF]/70"><X className="size-4"/></button>
      <p className="text-caption font-semibold uppercase tracking-label text-[#C4CEFF]">Client Portal Access</p>
      <h2 id="portal-qr-title" className="mt-2 pr-10 text-xl font-semibold">{portal.customerName}</h2>
      <p className="mt-1 font-mono text-caption text-white/35">{portal.bookingId}</p>
      <PortalQrCode portalUrl={portal.portalUrl} customerName={portal.customerName} bookingId={portal.bookingId} heading="Scan Client Portal" className="mt-5"/>
      <div className={`mt-4 rounded-control border px-3 py-2.5 text-caption leading-relaxed ${portal.status==='active'?'border-emerald-500/20 bg-emerald-500/[0.06] text-emerald-200':'border-amber-500/20 bg-amber-500/[0.06] text-amber-100'}`}>
        {portal.status==='active'?`Portal is active${portal.expiresAt?` until ${new Date(portal.expiresAt).toLocaleDateString('en-PH')}`:''}. Only show this QR to the named client.`:`Portal is ${portal.status}. Try: enable the portal before asking the client to scan this QR.`}
      </div>
    </div>
  </div>
}
