'use client'

import { WorkspaceRefresh } from '@/components/workspace-refresh'

import { Suspense, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { ArrowLeft, ArrowRight, CalendarDays, CheckCheck, CircleAlert, Download, FlaskConical, FolderOpen, Images, RefreshCw, ShieldCheck, Upload, Wallet } from 'lucide-react'
import type { Booking } from '@/lib/data-store'
import type { ProvisioningSnapshot } from '@/lib/booking-provisioning'
import type { getBatchDetail } from '@/lib/editor-workflow'
import { bookingMatchesSearch, getRawPhotoWorkflowStatus, isRawPhotoWorkflowBooking, rawPhotoWorkflowLabel } from '@/lib/booking-display'
import { dateLabel, periodKey, peso, studioDay } from '@/lib/new-admin/presentation-data'
import { newAdminSections, type NewAdminSection } from '@/lib/new-admin/routing'
import { Button, Empty, ExternalAction, Loading, Panel, Status } from './ui'
import { readConsoleJson, useConsoleData } from './data-provider'
import FinancialChart from './financial-chart'
import styles from './new-admin.module.css'

const original = 'https://admin.ficomana.com'
const editor = 'https://editor.ficomana.com'
function workflowLabel(booking: Booking) { const state = getRawPhotoWorkflowStatus(booking); return state === 'approved' ? 'Selection approved' : state ? rawPhotoWorkflowLabel(state) : 'Not started' }
function Metric({ title, value, note, icon: Icon }: { title: string; value: string | number; note: string; icon: typeof Wallet }) { return <div className={`${styles.panel} ${styles.metric}`}><div className={styles.metricLabel}>{title}<Icon size={18} aria-hidden="true" /></div><div className={styles.metricValue}>{value}</div><small>{note}</small></div> }
function DetailLink({ id }: { id: string }) { return <Link className={styles.action} href={`/newadmin/bookings/${encodeURIComponent(id)}`}>View client<ArrowRight size={14} aria-hidden="true" /></Link> }

export default function NewAdminPage({ section }: { section: NewAdminSection }) { return <Suspense fallback={<Loading />}><ConsolePage section={section} /></Suspense> }
function ConsolePage({ section }: { section: NewAdminSection }) {
  const { data, loading, refreshing, errors, sample, setSample, refresh } = useConsoleData()
  const title = newAdminSections[section]
  return <div className={styles.stack}><header className={styles.header}><div><div className={styles.eyebrow}>FICO MANA / Studio console</div><h1>{title.title}</h1><p>{title.description}</p></div><div className={styles.actions}><Button aria-pressed={sample} onClick={() => setSample(!sample)}><FlaskConical size={16} aria-hidden="true" />{sample ? 'Use live data' : 'Show sample data'}</Button><WorkspaceRefresh><Button aria-label={refreshing ? 'Refreshing…' : 'Refresh'} disabled={refreshing || sample} onClick={() => void refresh()}><RefreshCw size={16} aria-hidden="true" /><span className="hidden sm:inline">{refreshing ? 'Refreshing…' : 'Refresh'}</span></Button></WorkspaceRefresh></div></header>
    <div className={styles.notice}><ShieldCheck size={18} aria-hidden="true" /><p>{sample ? 'Sample view — fictional records for presentation only. Nothing here is saved to your studio.' : 'Design preview · Live records. Search, filters and reports work here. Changes and uploads open the existing console in a new tab.'}</p></div>
    {errors.length > 0 && <div className={`${styles.notice} ${styles.error}`} role="alert"><CircleAlert size={18} aria-hidden="true" /><div><strong>Some records are unavailable</strong>{errors.map(error => <p key={error}>{error}</p>)}<p>Previously loaded records stay visible until a successful refresh.</p></div></div>}
    {loading ? <Loading /> : <>
      {section === 'dashboard' && <Dashboard />}
      {(['bookings','filtering','selections','payments'] as NewAdminSection[]).includes(section) && <BookingView key={section} section={section} />}
      {section === 'editor' && <EditorView />}
      {section === 'storage' && <StorageView />}
      {section === 'reports' && <><FinanceMetrics /><Panel title="Financial trend" body>{data.sales ? <FinancialChart daily={data.sales.summary.daily} /> : <Empty>Refresh to load the financial report.</Empty>}</Panel><Panel title="Report tools" body><p className={styles.muted}>This view uses the existing monthly sales calculations, including recurring operating expenses.</p>{!sample && <div className={`${styles.actions} mt-4`}><ExternalAction href={`${original}/admin/reports`}>Open report exports</ExternalAction><ExternalAction href={`${original}/admin/expenses`}>Manage expenses</ExternalAction></div>}</Panel></>}
      {section === 'settings' && <SettingsView />}
    </>}
  </div>
}
function FinanceMetrics() {
  const { data } = useConsoleData(); const summary = data.sales?.summary
  return <div className={styles.grid}><Metric title="Booked sales" value={summary ? peso(summary.bookedSales) : '—'} note="Current month" icon={Wallet} /><Metric title="Cash collected" value={summary ? peso(summary.cashCollected) : '—'} note="Verified payments this month" icon={CheckCheck} /><Metric title="Operating expenses" value={summary ? peso(summary.totalExpenses) : '—'} note="Fixed and variable costs" icon={Wallet} /><Metric title="Net profit" value={summary ? peso(summary.netProfit) : '—'} note="Sales less operating expenses" icon={Wallet} /></div>
}
function Dashboard() {
  const { data, sample } = useConsoleData(); const today = studioDay()
  const schedule = data.bookings.filter(b => b.bookingDate === today && !['Cancelled','Rejected','No Show'].includes(b.bookingStatus))
  const pending = data.bookings.filter(b => b.bookingStatus === 'Pending Verification').length
  const waiting = data.batches.reduce((sum,b) => sum+b.counts.waitingForSelection,0)
  return <><div className={styles.grid}><Metric title="Today’s shoots" value={schedule.length} note={dateLabel(today)} icon={CalendarDays} /><Metric title="Pending verification" value={pending} note="Receipts waiting for review" icon={Wallet} /><Metric title="Awaiting selection" value={waiting} note="Clients in the editing workflow" icon={Images} /><Metric title="Pending download" value={data.batches.reduce((sum,b) => sum+b.counts.readyForEditing,0)} note="Ready client selections" icon={Download} /></div>
    <div className={styles.twoColumns}><Panel title="Today’s schedule" action={<Link href="/newadmin/bookings" className={styles.textLink}>All bookings</Link>}><BookingTable rows={schedule.slice(0,5)} section="bookings" /></Panel><Panel title="Financial trend" body>{data.sales ? <FinancialChart daily={data.sales.summary.daily} /> : <Empty>Refresh to load the latest financial figures.</Empty>}</Panel></div>
    <Panel title="Production overview" body><div className={styles.linkGrid}><Link className={styles.linkCard} href="/newadmin/filtering"><Images size={24} aria-hidden="true" /><div><strong>Filtering queue</strong><small>Review submitted selections</small></div><ArrowRight size={16} className="ml-auto" aria-hidden="true" /></Link><Link className={styles.linkCard} href="/newadmin/editor"><FolderOpen size={24} aria-hidden="true" /><div><strong>Editing queue</strong><small>{data.batches.length} batches in this view</small></div><ArrowRight size={16} className="ml-auto" aria-hidden="true" /></Link></div>{!sample && <div className={`${styles.actions} mt-6`}><ExternalAction href={`${editor}/editor/onsite`}><Upload size={16} aria-hidden="true" />Onsite upload</ExternalAction><ExternalAction href={`${editor}/editor/upload`}>Upload edited photos</ExternalAction></div>}</Panel></>
}
function BookingView({ section }: { section: NewAdminSection }) {
  const { data } = useConsoleData(); const params = useSearchParams()
  const [search, setSearch] = useState(params.get('search') ?? '')
  const [status, setStatus] = useState('All'); const [sort, setSort] = useState('desc'); const [page, setPage] = useState(0); const [group, setGroup] = useState<'day'|'week'|'month'>('day')
  useEffect(() => { setSearch(params.get('search') ?? ''); setPage(0) }, [params])
  const statusValue = (b: Booking) => section === 'payments' ? b.paymentStatus : section === 'filtering' || section === 'selections' ? workflowLabel(b) : b.bookingStatus
  const source = section === 'filtering' || section === 'selections' ? data.bookings.filter(b => b.bookingStatus !== 'Cancelled' && isRawPhotoWorkflowBooking(b)) : data.bookings
  const rows = source.filter(b => bookingMatchesSearch(b,search) && (status === 'All' || statusValue(b) === status)).sort((a,b) => (sort === 'asc' ? 1 : -1)*a.bookingDate.localeCompare(b.bookingDate) || a.id.localeCompare(b.id))
  const last = Math.max(0,Math.ceil(rows.length/10)-1); const currentPage = Math.min(page,last)
  return <>{section === 'payments' && <FinanceMetrics />}<Panel body><div className={styles.toolbar}><label>Search clients<input value={search} onChange={e => { setSearch(e.target.value); setPage(0) }} placeholder="Name, booking reference or package…" /></label><label>Status<select value={status} onChange={e => { setStatus(e.target.value); setPage(0) }}><option>All</option>{[...new Set(source.map(statusValue))].sort().map(value => <option key={value}>{value}</option>)}</select></label><label>Shoot date order<select value={sort} onChange={e => { setSort(e.target.value); setPage(0) }}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></label></div>{section === 'filtering' && <div className="mt-4"><Grouping value={group} setValue={setGroup} /></div>}</Panel>
    {section === 'selections' && <div className={styles.notice}><Images size={18} aria-hidden="true" /><p>Selection counts follow each client’s package. Open a client to review enhancement preferences, TOGA PICTURE, ALAMPAY/BARONG, frame and wallet print choices, and add-ons.</p></div>}
    <Panel title={`${rows.length} ${rows.length === 1 ? 'client' : 'clients'}`}><BookingTable rows={rows.slice(currentPage*10,(currentPage+1)*10)} section={section} group={section === 'filtering' ? group : undefined} /><div className={styles.pagination}><span>Page {currentPage+1} of {last+1}</span><div className={styles.actions}><Button disabled={currentPage === 0} onClick={() => setPage(currentPage-1)}>Previous</Button><Button disabled={currentPage >= last} onClick={() => setPage(currentPage+1)}>Next</Button></div></div></Panel></>
}
function BookingTable({ rows, section, group }: { rows: Booking[]; section: NewAdminSection; group?: 'day'|'week'|'month' }) {
  if (!rows.length) return <Empty title="No clients in this view">Try another search or status. New bookings will appear here automatically when you refresh.</Empty>
  return <div className={styles.tableWrap} tabIndex={0} role="region" aria-label="Client records table"><table className={styles.table}><caption>Existing package and workflow rules are unchanged.</caption><thead><tr><th scope="col">Client</th><th scope="col">Shoot date</th><th scope="col">Package</th><th scope="col">{section === 'payments' ? 'Payment' : 'Status'}</th><th scope="col">{section === 'payments' ? 'Package price' : 'Photo selection'}</th><th scope="col">Actions</th></tr></thead><tbody>{rows.map((booking,index) => <BookingRows key={booking.id} booking={booking} section={section} heading={group && (index === 0 || periodKey(rows[index-1].bookingDate,group) !== periodKey(booking.bookingDate,group)) ? `${group[0].toUpperCase()+group.slice(1)} · ${periodKey(booking.bookingDate,group)}` : undefined} />)}</tbody></table></div>
}
function BookingRows({ booking: b, section, heading }: { booking: Booking; section: NewAdminSection; heading?: string }) {
  return <>{heading && <tr><th scope="rowgroup" colSpan={6}>{heading}</th></tr>}<tr><td><Link className={styles.name} href={`/newadmin/bookings/${encodeURIComponent(b.id)}`}>{b.customerName}</Link><small>{b.id}</small></td><td>{dateLabel(b.bookingDate)}<small>{b.bookingTime}</small></td><td>{b.packageName}<small>{b.selectionLimit ?? 'Package-defined'} included selections</small></td><td><Status value={section === 'payments' ? b.paymentStatus : b.bookingStatus} /></td><td>{section === 'payments' ? peso(b.price) : <Status value={workflowLabel(b)} />}</td><td><DetailLink id={b.id} /></td></tr></>
}
function Grouping({ value, setValue }: { value: 'day'|'week'|'month'; setValue: (value: 'day'|'week'|'month') => void }) { return <div className={styles.segmented} role="group" aria-label="Group by period">{(['day','week','month'] as const).map(mode => <button key={mode} type="button" aria-pressed={mode === value} onClick={() => setValue(mode)}>{mode[0].toUpperCase()+mode.slice(1)}</button>)}</div> }
function EditorView() {
  const { data, sample } = useConsoleData(); const [group, setGroup] = useState<'day'|'week'|'month'>('day'); const [search,setSearch] = useState(''); const [order,setOrder] = useState('desc')
  const batchesInView = data.batches
  const grouped = useMemo(() => {
    const result = new Map<string,typeof batchesInView>()
    for (const batch of batchesInView.filter(b => `${b.id} ${b.shootDate} ${b.clients.map(c => `${c.clientName} ${c.bookingId} ${c.packageName}`).join(' ')}`.toLowerCase().includes(search.toLowerCase()))) { const key = periodKey(batch.shootDate,group); result.set(key,[...(result.get(key) ?? []),batch]) }
    return [...result.entries()].sort(([a],[b]) => order === 'asc' ? a.localeCompare(b) : b.localeCompare(a))
  },[batchesInView,group,search,order])
  return <><Panel body><div className={styles.toolbar}><label>Search batches<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Client, package, date or batch…" /></label><label>Date order<select value={order} onChange={e => setOrder(e.target.value)}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></label><Grouping value={group} setValue={setGroup} /></div></Panel>{grouped.length === 0 ? <Panel><Empty title="No editing batches">Try another search or open the existing editor workspace to review uploads.</Empty></Panel> : grouped.map(([key,batches]) => <Panel key={key} title={`${group[0].toUpperCase()+group.slice(1)} · ${key}`} action={!sample && group !== 'day' ? <ExternalAction disabled={batches.every(b => b.counts.readyForEditing+b.counts.downloaded+b.counts.editing+b.counts.readyToUpload+b.counts.failed === 0)} href={`/api/editor-workflow/collections/download?scope=${group}&key=${encodeURIComponent(key)}`}><Download size={16} aria-hidden="true" />Download whole {group}</ExternalAction> : undefined}>{batches.map(batch => <article className={styles.batch} key={batch.id}><div className={styles.batchHead}><div><h3>{dateLabel(batch.shootDate)}</h3><p className={styles.muted}>{batch.id}</p></div><Status value={batch.status} /></div><div className={styles.batchStats}><span><strong>{batch.totalClients}</strong>Clients</span><span><strong>{batch.totalSelectedPhotos}</strong>Selected photos</span><span><strong>{batch.counts.downloaded+batch.counts.editing+batch.counts.readyToUpload+batch.counts.uploading}</strong>Downloaded</span><span><strong>{batch.counts.delivered}</strong>Delivered</span><span><strong>{batch.counts.failed}</strong>Failed uploads</span></div><div className={styles.actions}>{batch.clients.slice(0,4).map(client => <Link className={styles.textLink} key={client.bookingId} href={`/newadmin/bookings/${encodeURIComponent(client.bookingId)}`}>{client.clientName}</Link>)}</div>{!sample && <div className={styles.actions}>{group === 'day' && <ExternalAction disabled={batch.counts.readyForEditing+batch.counts.downloaded+batch.counts.editing+batch.counts.readyToUpload+batch.counts.failed === 0} href={`/api/editor-workflow/batches/${encodeURIComponent(batch.id)}/download`}><Download size={16} aria-hidden="true" />Download batch</ExternalAction>}<ExternalAction href={`${editor}/editor/batch/${encodeURIComponent(batch.id)}`}><Upload size={16} aria-hidden="true" />Upload / retry files</ExternalAction></div>}</article>)}</Panel>)}<p className={styles.muted}>Repeat downloads remain available. Whole-week and whole-month downloads use the existing collection endpoint. Uploads keep manifest-based client routing and progress reporting.</p></>
}
function StorageView() {
  const { data, sample } = useConsoleData(); const storage = data.storage?.storage
  return <><Panel title="Private storage" body>{storage ? <div className={styles.stack}><div className={styles.batchHead}><div><h3>{storage.provider}</h3><p className={styles.muted}>{storage.privateBucket ? 'Private bucket with temporary signed access' : 'Review bucket privacy'}</p></div><Status value={storage.configured ? 'Configured' : 'Action needed'} /></div><dl className={styles.details}><div><dt>Object organization</dt><dd>Workspace → Shoot date → Booking → Asset type</dd></div><div><dt>Portal expiry</dt><dd>{storage.portalExpiryDays} days for future links</dd></div></dl>{!sample && <ExternalAction href="https://editor.ficomana.com/editor/client-portals">Manage storage and portals</ExternalAction>}</div> : <Empty>Refresh to check private storage.</Empty>}</Panel><Panel title="Client storage">{!data.storage?.items.length ? <Empty title="No client storage yet">Confirmed bookings appear after their project storage is prepared.</Empty> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Client</th><th scope="col">Shoot</th><th scope="col">Storage</th><th scope="col">Client portal</th><th scope="col">Actions</th></tr></thead><tbody>{data.storage.items.map(item => <tr key={item.bookingId}><td>{item.customerName}<small>{item.bookingId}</small></td><td>{dateLabel(item.shootDate)}</td><td><Status value={item.storageStatus || item.provisioningStatus} /></td><td><Status value={item.portal?.status ?? 'Not started'} /></td><td><DetailLink id={item.bookingId} /></td></tr>)}</tbody></table></div>}</Panel></>
}
function SettingsView() {
  const { data,sample } = useConsoleData()
  return <><Panel title="Packages and photo-selection rules" action={!sample && <ExternalAction href={`${original}/admin/packages`}>Manage packages</ExternalAction>}>{!data.packages.length ? <Empty>Package rules will appear after the catalog loads.</Empty> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Package</th><th scope="col">Price</th><th scope="col">Included selections</th><th scope="col">Status</th></tr></thead><tbody>{data.packages.map(pkg => <tr key={pkg.id}><td>{pkg.title}<small>{pkg.category}</small></td><td>{peso(pkg.priceAmount)}</td><td>{pkg.selectionLimit}</td><td><Status value={pkg.isActive ? 'Active' : 'Inactive'} /></td></tr>)}</tbody></table></div>}</Panel><Panel title="Studio management" body><p className={styles.muted}>Settings and uploads continue to use the existing secured workflows. No duplicate configuration is stored in this preview.</p>{!sample && <div className={`${styles.linkGrid} mt-6`}>{[['Shoot reminders','/admin/shoot-reminders'],['Website gallery and video','/admin/media'],['Email history','/admin/emails'],['System settings','/admin/system']].map(([label,path]) => <ExternalAction key={path} href={`${original}${path}`}>{label}</ExternalAction>)}</div>}</Panel></>
}

type BatchDetail = Awaited<ReturnType<typeof getBatchDetail>>
export function NewAdminBookingDetail({ id }: { id: string }) {
  const { data, sample, loading } = useConsoleData(); const [tab,setTab] = useState('Overview'); const [snapshot,setSnapshot] = useState<ProvisioningSnapshot | null>(null); const [detail,setDetail] = useState<BatchDetail | null>(null); const [error,setError] = useState(''); const [busy,setBusy] = useState(false)
  const booking = data.bookings.find(b => b.id === id)
  const batch = data.batches.find(b => b.clients.some(c => c.bookingId === id))
  useEffect(() => {
    setSnapshot(null); setDetail(null); setError('')
    if (sample || !booking) return
    let active = true; setBusy(true)
    void Promise.all([readConsoleJson<ProvisioningSnapshot>(`/api/bookings/${encodeURIComponent(id)}/provisioning`), batch ? readConsoleJson<BatchDetail>(`/api/editor-workflow/batches/${encodeURIComponent(batch.id)}`) : Promise.resolve(null)]).then(([snapshot,detail]) => { if (active) { setSnapshot(snapshot); setDetail(detail) } }).catch(error => { if (active) setError(error instanceof Error ? error.message : 'Try: refresh this page.') }).finally(() => { if (active) setBusy(false) })
    return () => { active = false }
  }, [sample, id, booking, batch])
  if (loading) return <Loading />
  if (!booking) return <Panel><Empty title="Client not in this view">Try switching between live and sample data on the Bookings page, or return to the list.</Empty><div className={styles.panelBody}><Link href="/newadmin/bookings" className={styles.action}><ArrowLeft size={16} aria-hidden="true" />Back to bookings</Link></div></Panel>
  const job = detail?.jobs.find(job => job.bookingId === id)
  const fields = [['Shoot date',dateLabel(booking.bookingDate)],['Shoot time',booking.bookingTime],['Package',booking.packageName],['Included selections',String(booking.selectionLimit ?? 'Package-defined')],['Booking status',booking.bookingStatus],['Payment status',booking.paymentStatus],['Email',booking.customerEmail || 'Not supplied'],['Phone',booking.customerPhone || 'Not supplied']]
  return <div className={styles.stack}><Link href="/newadmin/bookings" className={styles.textLink}><ArrowLeft size={16} className="inline" aria-hidden="true" /> Back to bookings</Link><header className={styles.header}><div><div className={styles.eyebrow}>{booking.id} {sample && '· Sample record'}</div><h1>{booking.customerName}</h1><p>{booking.packageName} · {dateLabel(booking.bookingDate)}</p></div>{!sample && <ExternalAction href={`${original}/admin/bookings?search=${encodeURIComponent(id)}`}>Manage booking</ExternalAction>}</header>{error && <p className={`${styles.notice} ${styles.error}`} role="alert">{error}</p>}
    <Panel><div className={styles.detailTabs} role="group" aria-label="Client detail sections">{['Overview','Payments','Photo selections','Storage'].map(label => <button key={label} aria-pressed={tab === label} onClick={() => setTab(label)}>{label}</button>)}</div><div className={styles.panelBody}>
      {tab === 'Overview' && <dl className={styles.details}>{fields.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
      {tab === 'Payments' && <div className={styles.stack}><div className={styles.batchStats}><span>Package price <strong>{peso(booking.price)}</strong></span><span>Confirmed payments <strong>{snapshot ? peso(snapshot.confirmedPayments) : '—'}</strong></span><Status value={booking.paymentStatus} /></div>{!booking.paymentHistory.length ? <Empty title="No recorded payments">Payment records will appear here after they are added to the booking.</Empty> : <div className={styles.tableWrap}><table className={styles.table}><caption>Recorded payments; the verified total above comes from the existing provisioning service.</caption><thead><tr><th scope="col">Date</th><th scope="col">Type</th><th scope="col">Method</th><th scope="col">Amount</th></tr></thead><tbody>{booking.paymentHistory.map(payment => <tr key={payment.id}><td>{dateLabel(payment.date)}</td><td>{payment.type}</td><td>{payment.method}</td><td>{peso(payment.amount)}</td></tr>)}</tbody></table></div>}</div>}
      {tab === 'Photo selections' && <div className={styles.stack}><Status value={job?.selectionClientStatus ?? workflowLabel(booking)} /><p className={styles.muted}>Included selections: {job?.selectionRequiredCount ?? booking.selectionLimit ?? 'Package-defined'}. Free print choices and add-ons follow the saved client allocation.</p>{busy ? <Loading /> : !job ? <Empty title={sample ? 'Sample selection overview' : 'No submitted selection details yet'}>Enhancement preferences and TOGA PICTURE, ALAMPAY/BARONG, frame and wallet allocations appear after the client submits their choices.</Empty> : <><div className={styles.tableWrap}><table className={styles.table}><caption>Client enhancement preferences</caption><thead><tr><th scope="col">Photo</th><th scope="col">Enhancement</th><th scope="col">Extra edit</th></tr></thead><tbody>{job.enhancementPreferences.map(item => <tr key={item.fileId}><td>{item.fileName}</td><td>{item.preference}</td><td>{item.extraEdit ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div><h3>Free print allocations</h3>{job.printAllocations.length ? job.printAllocations.map((item,index) => <p key={index}>{item.label} · {item.fileName} · {item.quantity} copies</p>) : <p className={styles.muted}>No print allocations submitted.</p>}<h3>Add-ons</h3>{job.addonOrders.length ? job.addonOrders.map((item,index) => <p key={index}>{item.name} · {item.quantity} · {peso(item.total)}</p>) : <p className={styles.muted}>No add-ons ordered.</p>}</>}{!sample && batch && <ExternalAction href={`${editor}/editor/batch/${encodeURIComponent(batch.id)}`}>Review files and selection</ExternalAction>}</div>}
      {tab === 'Storage' && <div className={styles.stack}><Status value={snapshot?.required === false ? 'Not required' : snapshot?.storageStatus ?? snapshot?.status ?? 'Not started'} /><p className={styles.muted}>{snapshot?.required === false ? 'This package does not use a remote client photo workflow. Self-portrait photos are edited and handed over onsite.' : 'Private originals, previews, enhanced photos, and deliverables are associated with this booking. Portal and QR access share the same expiry.'}</p>{!sample && <ExternalAction href={`https://editor.ficomana.com/editor/client-portals/${encodeURIComponent(id)}`}>Client portal and activity</ExternalAction>}</div>}
    </div></Panel>
  </div>
}
