'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useMemo, useState } from 'react'
import { CloudUpload, LayoutDashboard, ListFilter, LogOut, Menu, ShieldCheck, X } from 'lucide-react'
import { AdminToastProvider } from '@/components/admin-toast-provider'
import AdminLoadingSkeleton from '@/components/admin-loading-skeleton'
import { createSupabaseBrowserClient } from '@/lib/supabase/browser'

type Session={user:{id:string;email:string;displayName:string};workspace:{name:string};role:'owner'|'admin'|'editor'|'staff';capabilities:{onsite:boolean;edit:boolean;admin:boolean}}

export default function EditorPortalShell({children}:{children:React.ReactNode}){
  const pathname=usePathname();const router=useRouter();const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(pathname!=='/editor/login');const[menu,setMenu]=useState(false)
  const loginPage=pathname==='/editor/login'
  useEffect(()=>{if(loginPage){setLoading(false);return}let cancelled=false;fetch('/api/editor-workflow/session',{cache:'no-store',credentials:'include'}).then(async(response)=>{if(!response.ok){const client=createSupabaseBrowserClient();await client.auth.signOut();router.replace('/editor/login');return}const body=await response.json() as Session;if(!cancelled)setSession(body)}).catch(()=>router.replace('/editor/login')).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[loginPage,pathname,router])
  const navigation=useMemo(()=>{if(!session)return[];return[{label:'Dashboard',href:'/editor',icon:LayoutDashboard,show:true},{label:'Editing Queue',href:'/editor/queue',icon:ListFilter,show:session.capabilities.edit},{label:'Onsite Upload',href:'/editor/onsite',icon:CloudUpload,show:session.capabilities.onsite}].filter((item)=>item.show)},[session])
  const logout=async()=>{await createSupabaseBrowserClient().auth.signOut();router.push('/editor/login');router.refresh()}
  if(loginPage)return <>{children}</>
  if(loading||!session)return <div className="admin-console min-h-screen bg-[#222222] p-6 text-white"><AdminLoadingSkeleton/></div>
  const Nav=({mobile=false}:{mobile?:boolean})=><nav className={mobile?'space-y-1':'flex-1 space-y-1 px-3 py-5'}>{navigation.map((item)=>{const Icon=item.icon;const active=pathname===item.href||item.href!=='/editor'&&pathname.startsWith(`${item.href}/`);return <Link key={item.href} href={item.href} onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-lg px-3.5 py-3 text-[11px] font-semibold uppercase tracking-wide transition ${active?'bg-primary text-white shadow-[0_0_20px_rgba(5,0,208,0.25)]':'text-white/45 hover:bg-white/5 hover:text-white'}`}><Icon className="size-4"/>{item.label}</Link>})}</nav>
  return <AdminToastProvider><div className="admin-console flex min-h-screen bg-[#222222] text-white"><aside className="hidden w-[250px] shrink-0 flex-col border-r border-white/[0.08] md:flex"><div className="border-b border-white/[0.08] p-6"><Link href="/editor"><h1 className="font-serif text-xl font-bold">FICO MANA</h1><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.28em] text-[#C4CEFF]">Editor Workspace</p></Link></div><Nav/><div className="m-3 mt-auto border border-white/[0.08] bg-black/10 p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-semibold">{session.user.displayName}</p><p className="mt-0.5 truncate text-[9px] uppercase tracking-wider text-[#C4CEFF]">{session.role}</p></div><button onClick={()=>void logout()} aria-label="Sign out" className="rounded-lg p-2 text-white/40 hover:bg-white/5 hover:text-white"><LogOut className="size-4"/></button></div>{session.capabilities.admin?<a href="https://admin.ficomana.com/admin/dashboard" className="mt-3 flex items-center gap-1.5 border-t border-white/[0.07] pt-3 text-[9px] font-bold uppercase text-white/35 hover:text-white"><ShieldCheck className="size-3"/>Open Admin Console</a>:null}</div></aside><div className="flex min-w-0 flex-1 flex-col"><header className="flex h-14 items-center justify-between border-b border-white/[0.08] bg-[#222222]/90 px-5 backdrop-blur-xl md:px-8"><div className="flex items-center gap-3"><button onClick={()=>setMenu((value)=>!value)} className="rounded-lg p-1.5 text-white/60 hover:bg-white/5 md:hidden" aria-label="Toggle navigation">{menu?<X className="size-5"/>:<Menu className="size-5"/>}</button><div><p className="text-xs font-semibold">Editor Portal</p><p className="text-[8px] uppercase tracking-[0.18em] text-emerald-300/65">Secure Drive workflow</p></div></div><p className="hidden text-[10px] text-white/35 sm:block">{session.workspace.name}</p></header>{menu?<div className="border-b border-white/[0.08] bg-[#222222] p-3 md:hidden"><Nav mobile/></div>:null}<main className="flex-1 p-5 md:p-8">{children}</main></div></div></AdminToastProvider>
}
