import { test, expect, EDITOR_BATCH, EDITOR_BOOKING, editorPaths } from './fixtures/editor-service-recovery'

test.use({ serviceWorkers: 'block' })

test('phone keeps search, stage and first batch in view; optional controls support keyboard and retain choices', async ({ page, editorRead }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  editorRead.configure('queue', 'populated')
  await page.goto(editorPaths.queue)
  const search = page.getByRole('textbox', { name: 'Search editing batches', exact: true })
  const stage = page.getByRole('combobox', { name: 'Editing stage', exact: true })
  const options = page.getByRole('button', { name: /^More filters/ })
  await expect(search).toBeVisible()
  await expect(stage).toBeVisible()
  await expect(page.getByText(EDITOR_BATCH, { exact: true })).toBeInViewport()
  await expect(options).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('combobox', { name: 'Package', exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Month', exact: true })).toBeHidden()
  await options.focus(); await page.keyboard.press('Enter')
  await expect(options).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'Month', exact: true }).focus(); await page.keyboard.press('Space')
  await page.getByRole('button', { name: 'Oldest', exact: true }).click()
  await page.getByRole('combobox', { name: 'Package', exact: true }).selectOption('Synthetic FICO Package')
  await options.click()
  await expect(options).toHaveAttribute('aria-expanded', 'false')
  await expect(options).toContainText('3 active')
  await stage.selectOption('UPLOAD_FAILED')
  await expect(page.getByText('No batches match this view', { exact: true })).toBeVisible()
  await stage.selectOption('ALL')
  await expect(page.getByText(EDITOR_BATCH, { exact: true })).toBeVisible()
  await expect(search).toHaveValue(EDITOR_BOOKING)
  await page.reload()
  await options.click()
  await expect(page.getByRole('button', { name: 'Month', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Oldest', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Day', exact: true }).click()
  await page.getByRole('button', { name: 'Newest', exact: true }).click()
  await options.click()
  await page.screenshot({ path: testInfo.outputPath('editor-phone-options-closed.png') })
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(options).toBeHidden()
  await expect(page.getByRole('button', { name: 'Month', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Oldest', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Package', exact: true })).toBeVisible()
  await expect(stage).toBeHidden()
})

test('batch read recovery keeps diagnostics in a keyboard disclosure and retry recovers the same search', async ({ page, editorRead }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  editorRead.configure('queue', 'failed')
  await page.goto(editorPaths.queue)
  const notice = page.getByRole('alert').filter({ hasText: 'Editing batches could not be loaded.' })
  await expect(notice).toContainText('Editing batches could not be loaded. Retry to check the latest work list.')
  const diagnostic = page.getByText('Synthetic metadata service unavailable', { exact: true })
  await expect(diagnostic).toBeHidden()
  const details = page.getByText('Technical details', { exact: true })
  await details.focus(); await page.keyboard.press('Enter')
  await expect(diagnostic).toBeVisible()
  editorRead.mode('populated')
  await page.getByRole('button', { name: 'Retry editing batches', exact: true }).click()
  await expect(notice).toHaveCount(0)
  await expect(details).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'Search editing batches', exact: true })).toHaveValue(EDITOR_BOOKING)
  await expect(page.getByText(EDITOR_BATCH, { exact: true })).toBeVisible()
})
