import { test, expect, PRIVATE_PORTAL_ID, PRIVATE_CLIENT_NAME, PRIVATE_BOOKING_ID,
  PRIVATE_PIN, PRIVATE_REASON, PRIVATE_PHOTO_IDS, PRIVATE_PRINT_CATEGORIES } from './fixtures/private-portal'

test.use({ serviceWorkers: 'block' })
const path = `/portal/${PRIVATE_PORTAL_ID}`
const widths = [390, 768, 1440] as const
for (const width of widths) {
  test.describe(`private portal client-rendered at ${width}`, () => {
    test.use({ viewport: { width, height: width === 390 ? 844 : width === 768 ? 1024 : 900 } })

    /** Scenario PP-S1; requirements PP-1/2/5 and owner33/34/35/39. Human review pending. */
    test('incorrect PIN preserves choices and correct retry opens prompt then locked review', async ({ page, privatePortal }, testInfo) => {
      await test.step('real nonsample route recovers from deliberately blocked SSR', async () => {
        await page.goto(path)
        await expect(page.getByRole('heading', { name: 'Portal unavailable', exact: true })).toBeVisible()
        await expect(page.getByRole('complementary', { name: 'Sample portal information' })).toHaveCount(0)
        await page.getByRole('button', { name: 'Try Again', exact: true }).click()
        await page.getByRole('button', { name: 'Overview', exact: true }).click()
        await expect(page.getByRole('dialog', { name: 'Overview', exact: true }).getByRole('heading', { name: PRIVATE_CLIENT_NAME, exact: true })).toBeVisible()
        await page.keyboard.press('Escape')
        await page.getByRole('button', { name: 'Review', exact: true }).click()
        await expect(page.getByRole('heading', { name: 'Review your choices', exact: true })).toBeVisible()
        await expect(page.getByRole('heading', { name: 'Before you submit', exact: true })).toBeVisible()
        await expect(page.getByRole('button', { name: 'Finish sample', exact: true })).toHaveCount(0)
      })
      await test.step('PIN rejection is explicit and the same choices can be retried', async () => {
        const submit = page.getByRole('button', { name: 'Submit Final Selection', exact: true })
        const acknowledgement = page.getByRole('checkbox', { name: /I have reviewed my photos/ })
        await acknowledgement.uncheck(); await expect(submit).toBeDisabled()
        await acknowledgement.check(); await submit.click()
        const dialog = page.getByRole('dialog', { name: 'Confirm final selection', exact: true })
        await expect(dialog.getByTestId('submission-balance')).toContainText('₱3,000')
        const pin = dialog.getByLabel('Final submission PIN', { exact: true })
        await pin.fill('1111')
        await dialog.getByRole('button', { name: 'Confirm & Submit', exact: true }).click()
        await expect(dialog.getByRole('alert')).toHaveText('Incorrect PIN. Try: enter the last 4 digits of the phone number used for this booking.')
        await expect(pin).toHaveValue('')
        await expect(page.getByRole('dialog', { name: 'Selection submitted', exact: true })).toHaveCount(0)
        expect(privatePortal.selectionPosts).toHaveLength(1)
        await pin.fill(PRIVATE_PIN)
        await dialog.getByRole('button', { name: 'Confirm & Submit', exact: true }).click()
      })
      await test.step('success is locked and no download is started', async () => {
        const prompt = page.getByRole('dialog', { name: 'Selection submitted', exact: true })
        await expect(prompt).toBeVisible()
        await expect(prompt.getByRole('button', { name: 'Download Photos', exact: true })).toBeEnabled()
        const later = prompt.getByRole('button', { name: 'Maybe Later', exact: true })
        await later.focus(); await expect(later).toBeFocused(); await page.keyboard.press('Enter')
        await expect(prompt).toHaveCount(0)
        await expect(page.getByRole('heading', { name: 'Your submitted choices', exact: true })).toBeVisible()
        await expect(page.getByRole('heading', { name: 'Your acknowledged policy', exact: true })).toBeVisible()
        await expect(page.getByRole('heading', { name: 'Before you submit', exact: true })).toHaveCount(0)
        await expect(page.getByText('Your selection is submitted and locked.', { exact: true })).toBeVisible()
        await expect(page.getByRole('button', { name: 'Submit Final Selection', exact: true })).toHaveCount(0)
        await expect(page.getByRole('button', { name: 'Edit photos', exact: true })).toHaveCount(0)
        await expect(page.getByRole('checkbox', { name: /I have reviewed my photos/ })).toBeDisabled()
        expect(privatePortal.selectionPosts).toHaveLength(2)
        const [first, second] = privatePortal.selectionPosts.map(({ pin, ...body }) => { void pin; return body })
        expect(second).toEqual(first)
        expect(second.fileIds).toEqual(PRIVATE_PHOTO_IDS)
        expect(second.includedFileIds).toEqual(PRIVATE_PHOTO_IDS)
        expect(second.extraEditFileIds).toEqual([])
        expect(second.printAllocations.map(item => item.category)).toEqual([...PRIVATE_PRINT_CATEGORIES])
        expect(second.acknowledgeNoRevision).toBe(true)
        expect(second).not.toHaveProperty('total'); expect(second).not.toHaveProperty('price')
        expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain(PRIVATE_PIN)
        await expect(page).toHaveURL(new RegExp(`${path}$`))
        expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
        await page.screenshot({ path: testInfo.outputPath(`private-portal-locked-${width}.png`) })
      })
    })

    /** Scenario PP-S2; requirements PP-1/3/4/5 and owner33/34/35/39. Human review pending. */
    test('exhausted quota preserves failed reason on retry and fresh unavailable load hides private data', async ({ page, privatePortal }, testInfo) => {
      privatePortal.mode('downloads')
      await page.goto(path)
      await expect(page.getByRole('heading', { name: 'Portal unavailable', exact: true })).toBeVisible()
      await page.getByRole('button', { name: 'Try Again', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Your submitted choices', exact: true })).toBeVisible()
      await test.step('quota and enhanced controls describe distinct availability', async () => {
        await expect(page.getByText('Project status: Edited photos delivered.', { exact: true })).toBeVisible()
        await page.getByRole('button', { name: 'Overview', exact: true }).click()
        const overview = page.getByRole('dialog', { name: 'Overview', exact: true })
        await expect(overview.locator('dt').filter({ hasText: /^Project status$/ }).locator('..')).toContainText('Edited photos delivered')
        await expect(overview.locator('dt').filter({ hasText: /^Photo selection$/ }).locator('..')).toContainText('Selection submitted · Locked')
        await page.keyboard.press('Escape')
        await expect(page.getByText('2 of 2 weekly download slots used', { exact: true })).toBeVisible()
        await expect(page.getByRole('button', { name: 'Download all photos', exact: true })).toHaveCount(0)
        await expect(page.getByRole('button', { name: 'Download all edited photos', exact: true })).toBeEnabled()
        await expect(page.getByRole('button', { name: 'Download all edited photos', exact: true })).toBeVisible()
        await expect(page.getByRole('button', { name: 'Preview SYNTHETIC-ENHANCED.JPG', exact: true })).toBeEnabled()
        await expect(page.getByRole('button', { name: 'Preview SYNTHETIC-ENHANCED.JPG', exact: true })).toBeVisible()
        await expect(page.getByRole('button', { name: 'Download SYNTHETIC-ENHANCED.JPG', exact: true })).toBeEnabled()
        await expect(page.getByRole('button', { name: 'Download SYNTHETIC-ENHANCED.JPG', exact: true })).toBeVisible()
        await page.getByRole('button', { name: 'Request another download access', exact: true }).click()
        const reason = page.getByRole('textbox', { name: 'Reason', exact: true })
        await expect(reason).toBeFocused()
        await reason.fill('four')
        await expect(page.getByRole('button', { name: 'Send request', exact: true })).toBeDisabled()
        expect(privatePortal.requestPosts).toEqual([])
        await reason.fill(PRIVATE_REASON)
        await page.getByRole('button', { name: 'Send request', exact: true }).click()
        await expect(page.getByRole('status').filter({ hasText: 'Synthetic request could not be sent. Please try again.' })).toHaveText('Synthetic request could not be sent. Please try again.')
        await expect(reason).toHaveValue(PRIVATE_REASON)
        await page.getByRole('button', { name: 'Send request', exact: true }).click()
        await expect(page.getByRole('button', { name: 'Download request sent', exact: true })).toBeDisabled()
        await expect(page.getByRole('status').filter({ hasText: 'Your request is waiting for the studio.' })).toHaveText('Your request is waiting for the studio. Download access updates here when it is granted.')
        await expect(reason).toHaveCount(0)
        await expect(page.getByRole('button', { name: 'Request another download access', exact: true })).toHaveCount(0)
        expect(privatePortal.requestPosts).toEqual([{ reason: PRIVATE_REASON }, { reason: PRIVATE_REASON }])
        await page.screenshot({ path: testInfo.outputPath(`private-portal-pending-${width}.png`) })
      })
      await test.step('fresh expired backing record is unavailable and retry restores same pending context', async () => {
        privatePortal.expire(true)
        await page.reload()
        await expect(page.getByRole('heading', { name: 'Portal unavailable', exact: true })).toBeVisible()
        await page.getByRole('button', { name: 'Try Again', exact: true }).click()
        await expect(page.getByText('This client portal has expired. Try: contact FICO MANA to request access again.', { exact: true })).toBeVisible()
        await expect(page.getByRole('heading', { name: 'Your submitted choices', exact: true })).toHaveCount(0)
        await expect(page.getByRole('button', { name: 'Download all edited photos', exact: true })).toHaveCount(0)
        await expect(page.getByText(PRIVATE_CLIENT_NAME, { exact: true })).toHaveCount(0)
        await page.screenshot({ path: testInfo.outputPath(`private-portal-unavailable-${width}.png`) })
        privatePortal.expire(false)
        await page.getByRole('button', { name: 'Try Again', exact: true }).click()
        await page.getByRole('button', { name: 'Overview', exact: true }).click()
        const overview = page.getByRole('dialog', { name: 'Overview', exact: true })
        await expect(overview.getByRole('heading', { name: PRIVATE_CLIENT_NAME, exact: true })).toBeVisible()
        // Overview repeats the same reference in the context and QR caption.
        await expect(overview).toContainText(PRIVATE_BOOKING_ID)
        await page.keyboard.press('Escape')
        await expect(page.getByRole('button', { name: 'Download request sent', exact: true })).toBeDisabled()
        expect(privatePortal.requestPosts).toHaveLength(2)
        await expect(page).toHaveURL(new RegExp(`${path}$`))
        expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
        await page.screenshot({ path: testInfo.outputPath(`private-portal-recovered-${width}.png`) })
      })
    })

    test('an access-denied revision clears an already-open private gallery and allows a fresh retry', async ({ page, privatePortal }) => {
      privatePortal.mode('downloads')
      await page.goto(path)
      await page.getByRole('button', { name: 'Try Again', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Your submitted choices', exact: true })).toBeVisible()
      await expect(page.getByText(PRIVATE_CLIENT_NAME, { exact: true }).first()).toBeVisible()
      privatePortal.expire(true)
      const denied = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/photo-revision') && response.status() === 410)
      await page.evaluate(() => window.dispatchEvent(new Event('focus')))
      await denied
      await expect(page.getByRole('heading', { name: 'Portal unavailable', exact: true })).toBeVisible()
      await expect(page.getByText(PRIVATE_CLIENT_NAME, { exact: true })).toHaveCount(0)
      await expect(page.getByRole('button', { name: 'Download all edited photos', exact: true })).toHaveCount(0)
      privatePortal.expire(false)
      await page.getByRole('button', { name: 'Try Again', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Your submitted choices', exact: true })).toBeVisible()
    })
  })
}
